### ISSUE TITLE
Update Git cloning tool to add YML into repo and push to Gitlab

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/unity-app-generator#14]
Update mcp_git_clone.sh to add YAML file to call unity-app-generator into clone of repo pushed to Gitlab. Place on a new branch instead of master.

**Comment by edwinsarkissian** [comment]
Git cloning tool is upgraded to take an optional input YAML pipeline file, add it to the repository to be cloned in MCP GitLab and clone the whole thing in MCP GitLab.  A basic YAML file is available, but it is not complete and needs to be improved over time.

**Comment by edwinsarkissian** [comment]
Done

**Comment by mcduffie** [comment]
The YAML file needs to be pushed onto a seperate branch, not the user's main branch

**Comment by edwinsarkissian** [comment]
This task is done.  A working version of the YML file is in this repository.  The last commit is https://github.com/unity-sds/unity-app-build-trigger/commit/8437fd8063c3991305d0175c5975df080c419814
