### ISSUE TITLE
Create Gitlab Project YML to call unity-app-generator

### ISSUE THREAD

**Issue by mcduffie** [unity-sds/unity-app-generator#7]
Acceptance Criteria:
- Gitlab runner can be triggered through API call
- Gitlab runner executes YML without error
- Gitlab runner successfully deploy and example application unity-sds/unity-ads-deployment#47

**Comment by edwinsarkissian** [comment]
Now, the unity-app-generator can be successfully installed in Amazon Linux.  The Python version issue, “sudo” issue, docker server connection problem … are all resolved.  A basic YAML file that can execute the first two unity app generator commands is created, but the file will need to be improved over time.

**Comment by mcduffie** [comment]
Where is this YAML file version controlled?

**Comment by edwinsarkissian** [comment]
This task is complete.  All unity-app-gen commands (init, docker-build, docker-push, cwl-build, cal-push) are called in this commit https://github.com/unity-sds/unity-app-build-trigger/commit/54963ada4c3586439a78e1874bb6ee09858aeff7
